### ISSUE TITLE
ImportError: cannot import name 'bytes_to_str' from 'pandas.compat'

### ISSUE THREAD

**Issue by coulanuk** [pydata/pandas-datareader#656]
Pandas 0.25.0 and latest Dev pandas-datareader (0.7.0+55.g874b385).
(Similar issue to #655)

/usr/local/lib/python3.7/dist-packages/pandas_datareader/base.py in
10 from pandas import read_csv, concat
11 from pandas.io.common import urlencode
---> 12 from pandas.compat import bytes_to_str
13
14 from pandas_datareader._utils import (RemoteDataError, SymbolWarning,

ImportError: cannot import name 'bytes_to_str' from 'pandas.compat' (/usr/local/lib/python3.7/dist-packages/pandas/compat/init.py)

**Work-around :**
roll back to prior version of Pandas 0.24.2
pip3 install --upgrade pandas==0.24.2

**Comment by Leslye777** [comment]
I have the same error. I tried everything possible to fix this, but nothing works yet

**Comment by bashtage** [comment]
I have pushed 0.7.1 which should fix this issue.

**Comment by coulanuk** [comment]
@bashtage (Kevin) Many thanks, I have installed 0.7.1 from pypi.
With pandas 0.25.  
But the error remains in this release (as the changes made in dev to base.py have not been applied?):

/usr/local/lib/python3.7/dist-packages/pandas_datareader/base.py in <module>
      9 from pandas import read_csv, concat
     10 from pandas.io.common import urlencode
---> 11 from pandas.compat import StringIO, bytes_to_str
     12 
     13 from pandas_datareader._utils import (RemoteDataError, SymbolWarning,

ImportError: cannot import name 'StringIO' from 'pandas.compat' (/usr/local/lib/python3.7/dist-packages/pandas/compat/__init__.py)

**Comment by bashtage** [comment]
I have upped 0.7.2 which imports in a clean environment.

**Comment by satoshi** [comment]
@bashtage I appreciate you working on this, however 0.7.2 still does not import.  I think the StringIO error is gone but bytes_to_str is still missing.

    $ python3 -m venv venv
    $ . venv/bin/activate
    $ pip3 install pandas-datareader

    # output skipped for brevity

    Installing collected packages: six, python-dateutil, pytz, numpy, pandas, idna, certifi, urllib3, chardet, requests, wrapt, lxml, pandas-datareader
    Successfully installed certifi-2019.6.16 chardet-3.0.4 idna-2.8 lxml-4.4.0 numpy-1.17.0 pandas-0.25.0 pandas-datareader-0.7.2 python-dateutil-2.8.0 pytz-2019.1 requests-2.22.0 six-1.12.0 urllib3-1.25.3 wrapt-1.11.2

    $ venv/bin/python3 
    Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
    [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pandas_datareader as pdr
    Traceback (most recent call last):

    # output skipped for brevity

      File "/home/satoshi/testdir/venv/lib/python3.6/site-packages/pandas_datareader/base.py", line 12, in <module>
        from pandas.compat import bytes_to_str
    ImportError: cannot import name 'bytes_to_str'
    >>>

**Comment by bashtage** [comment]
Try again.  I released from the wrong branch.

**Comment by satoshi** [comment]
@bashtage 0.7.3 works.  Thank you very much!

**Comment by fabiozolio** [comment]
@bashtage facing the same problem as @satoshi 

How can I fix that ? 

https://github.com/pydata/pandas-datareader/issues/656#issuecomment-515799439

**Comment by bashtage** [comment]
Have you upgraded to 0.7.3?

**Comment by bashtage** [comment]
0.7.3 didn't work with Python 2.7. 
0.7.4 should import for any supported Python.

**Comment by coulanuk** [comment]
@bashtage : 0.7.4 with Pandas 0.25.0 works for me now.  Many thanks.

**Comment by fabiozolio** [comment]
@bashtage but do I import 0.74? I don't understand how to do that.

**Comment by bashtage** [comment]
pip install pandas-datareader - - upgrade

**Comment by fabiozolio** [comment]
@bashtage It worked perfect. Thanks your help...
