### PR TITLE
Fix error ImportError: cannot import name 'reduce' from 'pandas_datareader.compat'

### LINKED ISSUE #974: ImportError: cannot import name 'reduce' from 'pandas_datareader.compat' when using pandas_datareader.wb
How to reproduce:
`from pandas_datareader import wb`

Error was introduced in the commit 30b6d8728b83f16f3133330b2d68d9afe79541ab that accidentally (?) deleted import of reduce function from functools:

> diff --git a/pandas_datareader/compat/__init__.py b/pandas_datareader/compat/__init__.py
index 5eba99d..0555141 100644
--- a/pandas_datareader/compat/__init__.py
+++ b/pandas_datareader/compat/__init__.py
@@ -1,5 +1,4 @@
-from distutils.version import LooseVersion
-from functools import reduce
+from packaging import version
 from io import StringIO
 from urllib.error import HTTPError

### PR DESCRIPTION
**Pull request by agcr**
Closes #974

- [x] closes #974
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] passes `black --check pandas_datareader`
- [ ] added entry to docs/source/whatsnew/vLATEST.txt

### CODE REVIEW

**Comment by bashtage** [comment]
Succeeded in #978
