### ISSUE TITLE
Import error when using Pandas 0.20.1

### ISSUE THREAD

**Issue by arose13** [pydata/pandas-datareader#305]
There is an `ImportError: cannot import name 'PandasError'` when you use pandas version 0.20.1. 

This is occurring on line 5 in _utils.py `from pandas.core.common import PandasError`

If there is anything I can do to help or fix it myself I'd love to!

Works with `pandas 0.19.2` but not with `pandas 0.20.1`

**Comment by jreback** [comment]
this is already fixed by #304

**Comment by yuqli** [comment]
Thanks. I came into a similar problem this morning and #304 solved this perfectly after I downloaded the latest github version 0.3.1. 

In case any newcomer like me with the same problem I post my error codes here 

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda/lib/python2.7/site-packages/pandas_datareader/data.py", line 7, in <module>
    from pandas_datareader.google.daily import GoogleDailyReader
  File "/anaconda/lib/python2.7/site-packages/pandas_datareader/google/daily.py", line 1, in <module>
    from pandas_datareader.base import _DailyBaseReader
  File "/anaconda/lib/python2.7/site-packages/pandas_datareader/base.py", line 11, in <module>
    from pandas.core.common import PandasError, is_number
ImportError: cannot import name PandasError`  

I downloaded the latest version with this code in terminal 
`pip install git+https://github.com/pydata/pandas-datareader.git`

Thanks for the post again.

**Comment by danger89** [comment]
Yea kinda strange, but the workaround using the latest source code from git fixed my import problem. I think they need to update the pip package...
