### ISSUE TITLE
import error while working with pandas v0.20.1

### ISSUE THREAD

**Issue by zhuoqiang** [pydata/pandas-datareader#324]
after upgrade pandas to v0.20.1, there is import error while using pandas-datareader lib:

```py
/lib/python3.6/site-packages/pandas_datareader/_utils.py in <module>()
      3 
      4 import pandas as pd
----> 5 from pandas.core.common import PandasError
      6 from pandas import to_datetime
      7 

ImportError: cannot import name 'PandasError'
```

from pandas doc, v0.20 changes the sub-module structure, see http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#pandas-errors

**Comment by jreback** [comment]
this was fixed by #304 

a new release will be issued soon
