### ISSUE TITLE
ImportError: cannot import name 'reduce' from 'pandas_datareader.compat' when using pandas_datareader.wb

### ISSUE THREAD

**Issue by agcr** [pydata/pandas-datareader#974]
How to reproduce:
`from pandas_datareader import wb`

Error was introduced in the commit 30b6d8728b83f16f3133330b2d68d9afe79541ab that accidentally (?) deleted import of reduce function from functools:

> diff --git a/pandas_datareader/compat/__init__.py b/pandas_datareader/compat/__init__.py
index 5eba99d..0555141 100644
--- a/pandas_datareader/compat/__init__.py
+++ b/pandas_datareader/compat/__init__.py
@@ -1,5 +1,4 @@
-from distutils.version import LooseVersion
-from functools import reduce
+from packaging import version
 from io import StringIO
 from urllib.error import HTTPError

**Comment by agcr** [comment]
Fixed in https://github.com/pydata/pandas-datareader/pull/978
